{
 "title": "Kubernetes Resources Copy",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{}, namespace)"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=~\"$namespace\"}, label_app)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_labels{label_app =~\"$workload\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "overview service : $workload.$namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Services",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_service_labels{namespace=~\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DaemonSets",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_daemonset_labels{namespace=~\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "StatefullSets",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_statefullsets_labels{namespace=~\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Deployments",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_deployment_labels{namespace=~\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod Running",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"} > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod Failed,Failed,Unknown",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_status_phase{namespace=~\"$namespace\", phase=~\"Failed|Pending|Unknown\"} > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod crash timeline",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "count(kube_pod_status_phase{namespace=~\"$namespace\", phase=~\"Failed|Pending|Unknown\"} > 0)"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_labels{namespace=~\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Container",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_container_info{namespace=~\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Job Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"} > 0) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "pod resource overview in namespace : $namespace",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "kube_pod_labels{namespace=~\"$namespace\"} - 0",
       "legendFormat": "pod"
      },
      {
       "expr": "sum by(pod) (\n    kube_pod_container_resource_requests{resource=\"cpu\",namespace=~\"$namespace\"}\n  )",
       "legendFormat": "usage"
      },
      {
       "expr": "sum by(pod) (\n    kube_pod_container_resource_requests{resource=\"memory\",namespace=~\"$namespace\"}\n  )",
       "legendFormat": "memory"
      },
      {
       "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[$__rate_interval])) / sum by(pod) (\n    kube_pod_container_resource_requests{resource=\"cpu\",namespace=~\"$namespace\"}\n  )",
       "legendFormat": "cpu used"
      },
      {
       "expr": "sum by(pod)(container_memory_working_set_bytes{namespace=~\"$namespace\",container!=\"POD\"}) /\nsum by(pod) (\n    kube_pod_container_resource_requests{resource=\"memory\",namespace=~\"$namespace\"}\n  )"
      },
      {
       "expr": "sum (rate(container_network_receive_bytes_total{namespace=~\"$namespace\"}[$__rate_interval])*8) by (pod)"
      },
      {
       "expr": "sum (rate(container_network_transmit_bytes_total{namespace=~\"$namespace\"}[$__rate_interval])*8) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(time() - kube_pod_start_time{namespace=~\"$namespace\"}) by(pod) ",
       "legendFormat": "uptime"
      }
     ]
    },
    {
     "title": "Client Request Volume",
     "type": "stat",
     "description": "Reporter source and destination",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{reporter=~\"source|destination\",destination_app=~\"$workload\"}[5m])), 0.001)"
      }
     ]
    },
    {
     "title": "Server Request Volume",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{reporter=\"destination\",destination_app=~\"$workload\"}[5m])), 0.001)"
      }
     ]
    },
    {
     "title": "Request Source Duration",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
       "legendFormat": "P50"
      },
      {
       "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
       "legendFormat": "P90"
      },
      {
       "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "Client Success Rate (non-5xx responses)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=~\"destination|source\",destination_app=~\"$workload\",response_code!~\"5.*\"}[5m])) / sum(irate(istio_requests_total{reporter=~\"destination|source\",destination_app=~\"$workload\"}[5m]))"
      }
     ]
    },
    {
     "title": "Server Success Rate (non-5xx responses)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"destination\",destination_app=~\"$workload\",response_code!~\"5.*\"}[5m])) / sum(irate(istio_requests_total{reporter=\"destination\",destination_app=~\"$workload\"}[5m]))"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
       "legendFormat": "P50"
      },
      {
       "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
       "legendFormat": "P90"
      },
      {
       "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "4xxs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"source\", source_app=~\"$workload\", response_code=~\"4.*\"}[1m]))"
      }
     ]
    },
    {
     "title": "5xxs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"source\", source_app=~\"$workload\", response_code=~\"5.*\"}[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "overview pod : $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current CPU Usage",
     "type": "stat",
     "description": "CPU Milicore",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "usage"
      },
      {
       "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{pod=~\"$pod\"}[$__rate_interval])) / sum by(pod) (\n    kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"$pod\", container=~\"$container\"}\n  )",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "Current Memory Usage",
     "type": "stat",
     "description": "CPU Milicore",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(pod) (container_memory_working_set_bytes{pod=~\"$pod\", container!=\"POD\", container=~\"$container\"})",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by(pod) (container_memory_working_set_bytes{pod=\"$pod\", container!=\"POD\"}) /\nsum by(pod) (\n    kube_pod_container_resource_requests{resource=\"memory\",pod=\"$pod\"}\n  )",
       "legendFormat": "Percentage"
      }
     ]
    },
    {
     "title": "Current Inbount Network",
     "type": "stat",
     "description": "CPU Milicore",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[1m])*8) by (pod)"
      }
     ]
    },
    {
     "title": "Current Outbound Network",
     "type": "stat",
     "description": "CPU Milicore",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[1m])*8) by (pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "cpu metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "$container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "repeat": "container",
     "fieldConfig": { "defaults": { "unit": "core" } },
     "targets": [
      {
       "expr": "sum by(pod, container) (rate(container_cpu_usage_seconds_total{pod=~\"$pod\", container=~\"$container\"}[$__rate_interval]))",
       "legendFormat": "cpu usage"
      },
      {
       "expr": "sum by(pod, container) (\n    kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"$pod\", container=~\"$container\"}\n  )",
       "legendFormat": "requests"
      },
      {
       "expr": "sum by(pod, container) (\n    kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"$pod\", container=~\"$container\"}\n  )",
       "legendFormat": "cpu limit"
      }
     ]
    }
   ]
  },
  {
   "title": "memory metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "$container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "repeat": "container",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\",container!=\"POD\",container=~\"$container\"}) by(pod)",
       "legendFormat": "usage"
      },
      {
       "expr": "sum by(pod, container) (\n    kube_pod_container_resource_requests{resource=\"memory\",pod=~\"$pod\",container=~\"$container\"}\n  )",
       "legendFormat": "request"
      },
      {
       "expr": "sum by(pod, container) (\n    kube_pod_container_resource_limits{resource=\"memory\",pod=~\"$pod\",container=~\"$container\"}\n  )",
       "legendFormat": "limits"
      }
     ]
    }
   ]
  },
  { "title": "elastic log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "log explorer",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "kubernetes.namespace : $namespace and kubernetes.labels.app : $workload",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "redis information",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum (redis_connected_clients{part_of=\"$namespace\"}) by (instance)"
    },
    {
     "expr": "sum (redis_memory_used_bytes{part_of=\"$namespace\"}) by (instance)  / sum by (instance) (redis_memory_max_bytes{part_of=\"$namespace\"}) * 100"
    },
    {
     "expr": "sum by (instance) (redis_memory_max_bytes{part_of=\"$namespace\"})"
    },
    {
     "expr": "sum by(instance) (rate(redis_net_input_bytes_total{part_of=\"$namespace\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(instance) (rate(redis_net_output_bytes_total{part_of=\"$namespace\"}[$__rate_interval]))"
    },
    {
     "expr": "sum (redis_db_keys{part_of=\"$namespace\"}) by (instance) - sum (redis_db_keys_expiring{part_of=\"$namespace\"}) by (instance)"
    },
    {
     "expr": "sum (redis_db_keys_expiring{part_of=\"$namespace\"}) by (instance)"
    }
   ]
  }
 ]
}